move script to the workflow itself

diff --git a/.github/workflows/reusable.yaml b/.github/workflows/reusable.yaml
--- a/.github/workflows/reusable.yaml
+++ b/.github/workflows/reusable.yaml
@@ -89,11 +89,11 @@ jobs:
           token: ${{ secrets.github-token }}
           ref: uffizzi
 
-      - name: Change image tag in kustomization.yaml
-        run: |
-          cd ${{ inputs.environments-root-dir }}/${{ inputs.environment-dir }}
-          kustomize edit set image "$(echo '${{ inputs.image }}' | tr '[:upper:]' '[:lower:]'):${{ inputs.tag }}"
-          cat kustomization.yaml
+      # - name: Change image tag in kustomization.yaml
+      #   run: |
+      #     cd ${{ inputs.environments-root-dir }}/${{ inputs.environment-dir }}
+      #     kustomize edit set image "$(echo '${{ inputs.image }}' | tr '[:upper:]' '[:lower:]'):${{ inputs.tag }}"
+      #     cat kustomization.yaml
 
       - name: Create Uffizzi Cluster
         env:
@@ -105,7 +105,53 @@ jobs:
           UFFIZZI_CLUSTER: pr-${{ inputs.pr-number }}
           UFFIZZI_OP: ${{inputs.operation}}
         run: |
-          ./script.sh $UFFIZZI_OP
+          #!/bin/bash
+          # Checking if the script received any argument
+          if [ $# -eq 0 ]; then
+              echo "No arguments provided"
+              echo "[create|delete]"
+              exit 1
+          fi
+
+          # Retrieve the operation from the script argument
+          operation=$1
+
+          # Handling the operation
+          if [ "$operation" = "create" ]; then
+              echo "Checking if uffizzi cluster ${UFFIZZI_CLUSTER} already exists"    
+              if docker run --rm \
+                  --env UFFIZZI_SERVER \
+                  --env REQUEST_TOKEN=${ACTIONS_ID_TOKEN_REQUEST_TOKEN} \
+                  --env REQUEST_TOKEN_URL=${ACTIONS_ID_TOKEN_REQUEST_URL} \
+                  ${UFFIZZI_IMAGE} cluster list | grep --quiet ${UFFIZZI_CLUSTER}
+              # If it already exists, fetch the `kubeconfig` to connect to it.
+              then
+                  echo "Cluster already existsUpdating kubeconfig to point to ${UFFIZZI_CLUSTER}"
+                  docker run --rm --env UFFIZZI_SERVER \
+                      --env REQUEST_TOKEN=${ACTIONS_ID_TOKEN_REQUEST_TOKEN} \
+                      --env REQUEST_TOKEN_URL=${ACTIONS_ID_TOKEN_REQUEST_URL} \
+                      --mount type=bind,source="$(pwd)",target=/home \
+                  ${UFFIZZI_IMAGE} cluster update-kubeconfig \
+                      --name=${UFFIZZI_CLUSTER} --kubeconfig="/home/kubeconfig"
+              else 
+                  echo "Creating ..."
+                  docker run --rm --env UFFIZZI_SERVER \
+                      --env REQUEST_TOKEN=${ACTIONS_ID_TOKEN_REQUEST_TOKEN} \
+                      --env REQUEST_TOKEN_URL=${ACTIONS_ID_TOKEN_REQUEST_URL} \
+                      --mount type=bind,source="$(pwd)",target=/home \
+                  ${UFFIZZI_IMAGE} cluster create \
+                      --name=${UFFIZZI_CLUSTER} --kubeconfig="/home/kubeconfig"
+              fi
+          elif [ "$operation" = "delete" ]; then
+              # Insert delete logic here
+              echo "Deleting..."
+          else
+              # Default case if none of the above cases match
+              echo "Invalid operation. Please provide either 'create' or 'delete'"
+              exit 1
+          fi
+
+          exit 0
 
       # - name: Post to a Slack channel
       #   id: slack
